### ISSUE TITLE
[NSML] 2 GPU 사용 관련

### ISSUE THREAD

**Issue by kaen2891** [hunminjeongeum-korean-competition-2021/voice-recognition-performance-evaluation#12]
# 주제
-  2GPU 사용이 불가능한 것 같습니다.

# 상황 (자세히 작성해주시면 좋습니다.)
- TASK가 2개라서 각각 1개씩 돌리려 하는데, 1개만 러닝이 가능하고 나머지 1개는 돌지 못하고 있습니다. 자원 문제로 뜨는데요,
- 이 때, 5~10분 정도 텀을 두고 다시 진행해도 불가능합니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 실행 코드: nsml run -d stt_1 -g 1 -c 7 -e main.py (문제 없이 돌아감)
- nsml run -d stt_2 -g 1 -c 7 -e main.py (자원 문제로 안돌아감)
![image](https://user-images.githubusercontent.com/46586785/136992212-b3260901-14fc-4118-a4ae-926b1342e587.png)

nsml ps 시 
![image](https://user-images.githubusercontent.com/46586785/136992355-ba439bb8-dc5c-4fd1-b14c-e7680bb12241.png)

1개만 돌고 있는데, 나머지 1개에 대해서 추가 작업을 진행하고자 하였는데 돌지 못하고 있습니다. 2개 할당으로 알고 있는데 해결 부탁드려도 될까요? @bluebrush @devsungmin 

# 기타 문의 사항
-

**Comment by devsungmin** [comment]
안녕하세요 @kaen2891 님

말씀해 주신 NSML측과 함께 확인 해 보겠습니다.

감사합니다.

**Comment by bluebrush** [comment]
@kaen2891 님, 
GPU 문제로 분석됩니다. 
해당 장비에 2개 gpu중 1개만 사용중인데, 1개가 utilization 이 100%인 상태인데요. 다른 node로 교체하도록 하겠습니다. 
완료되면 다시 메시지 남기도록 하겠습니다. 
```
Wed Oct 13 22:00:49 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  On   | 00000000:00:05.0 Off |                  Off |
| N/A   37C    P0    42W / 250W |      0MiB / 32510MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  On   | 00000000:00:06.0 Off |                  Off |
| N/A   59C    P0   190W / 250W |  18017MiB / 32510MiB |     84%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    1   N/A  N/A     63348      C   python                          18011MiB |
+-----------------------------------------------------------------------------+
```

**Comment by kaen2891** [comment]
네 부탁드리겠습니다. 감사합니다.

**Comment by bluebrush** [comment]
@kaen2891 님, 신규 노드로 변경되었습니다 
기존 노드는 반납예정인데, 반납시 기존 세션들이 삭제될 수 있는데, 이슈 없으실 지 확인부탁드립니다. 
현재는 신규 노드에서 docker image pull을 진행하고 있습니다. (cache 생성용, 사용 가능상태)
이후 생성되는 신규 세션부터 자동 변경됩니다.

**Comment by kaen2891** [comment]
@bluebrush 님 네 괜찮습니다. 감사합니다!

**Comment by kaen2891** [comment]
![image](https://user-images.githubusercontent.com/46586785/137156611-d97a6fa3-c250-468a-b4d3-aac31ab151dd.png)
@bluebrush님, 위 사진과 같이 뜬 상태인데 계속 기다려야 하는건가요?

NSML 사이트에서는 계속 allow라고만 뜹니다.
![image](https://user-images.githubusercontent.com/46586785/137157210-465e379e-bcf9-425e-ae95-46e8547b6e6e.png)


명령어: nsml run -d stt_1 -g 1 -c 7 -e main.py

**Comment by bluebrush** [comment]
@kaen2891 님, 
1. docker image 주소
2. `nsml status -r -v`
3. `nsml ps` 

3가지 알수있을까요? 
allocating은 image pull + package install 시간일 가능성이 높습니다.

**Comment by kaen2891** [comment]
@bluebrush 님,

1. #nsml: dacon/nia-pytorch:1.0 그리고 
```
from distutils.core import setup

setup(
    name='ladder_networks',
    version='1.0',
    install_requires=[
        'torch==1.7.1',        
        'python-Levenshtein==0.12.2',
        'transformers==4.11.2',
        'librosa==0.8.1'
    ]
)
```
기본 docker 사용 중입니다.

2. 
![image](https://user-images.githubusercontent.com/46586785/137159621-f9479593-1679-48cc-a9fd-cba903ca8f8a.png)

3. 
![image](https://user-images.githubusercontent.com/46586785/137159692-a5bf12d1-7ac1-4146-a8a8-2f7614614551.png)

입니다. 계속 기다리는 중이에요

**Comment by kaen2891** [comment]
@bluebrush 님,

약 20분 전에는 fail만 발생했는데 현재는 building docker image 중이라고 합니다.

**Comment by bluebrush** [comment]
@kaen2891 님, docker image 정상적으로 pull되었고, 내부에 pip install에 지정한 모듈 설치중으로 보여집니다.

**Comment by kaen2891** [comment]
@bluebrush 님,
이제 작동하는 것 같습니다. 2개 모두 문제 없이 돌아가고 있습니다.
늦은 밤까지 도와주셔서 감사합니다!
