### ISSUE TITLE
[NSML] nsml submit 중 에러 발생

### ISSUE THREAD

**Issue by Ldoun** [hunminjeongeum-korean-competition-2021/voice-recognition-performance-evaluation#14]
# 주제
- nsml submit -e train.py nia1016/stt_2/76 3220 해당 명령어로 submit 후 에러가 발생했습니다

# 상황 (자세히 작성해주시면 좋습니다.)
- submit을 위해 명령어 실행 후 아래와 같은 에러가 떴습니다. 다른 명령어들이 모든 GPU를 사용하고 있다는 에러를 띄우는 것을 보아 submit 명령어가 GPU를 사용중인것 같은데 더이상 로그를 볼 수 없어 올바르게 제출중인지 모르겠습니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
 ![image](https://user-images.githubusercontent.com/67096173/137253565-413a6e87-5e9f-4032-ba12-71ec5324e42f.png)
 ![image](https://user-images.githubusercontent.com/67096173/137254003-ebde8187-b7d1-42df-81c0-2464e27693da.png)

**Comment by 21jun** [comment]
`nsml ps` 명령어로 실행되고있는 세션 확인하신 다음, 
실행중인 세션이 있다면 `nsml rm -f "세션명"`으로 종료 하시면 될것 같습니다.

**Comment by Ldoun** [comment]
오 감사합니다

**Comment by Ldoun** [comment]
세션 종류하고 다시 submit 하니까 잘 작동하네요 감사합니다
