### ISSUE TITLE
[NSML] pretrain 모델 및 외부데이터 업로드 방법

### ISSUE THREAD

**Issue by senti-mkyu** [hunminjeongeum-korean-competition-2021/voice-recognition-performance-evaluation#15]
# 주제
- nsml로 pretrain 모델 업로드하는 방법

# 상황 (자세히 작성해주시면 좋습니다.)
- nsml run을 하면 해당 디렉토리의 모든 파일을 업로드하는 것 같습니다.
- pretrain 모델이나 외부 데이터를 사용하려면 이 방법을 통해 업로드하는 방법 밖에 없나요?
- 해당 방법을 사용하면 **total size < 300MB** 일때만 허용되던데, 그 보다 큰 모델을 사용하려면 Docker image로 만들어서 push해야할까요? 아니면 nsml 콘솔에서 처리 가능한 방법이 있을까요?

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- None

# 기타 문의 사항
- None

감사합니다.

**Comment by bluebrush** [comment]
@aod1310 님, 일단 docker image에 포함시키는 방식을 먼저 검토하시는게 좋을 것 같습니다.

**Comment by senti-mkyu** [comment]
@bluebrush 감사합니다 :)
