### ISSUE TITLE
[Dataset] 외부데이터 사용시 검증을 위한 제출 여부 

### ISSUE THREAD

**Issue by jade0520** [hunminjeongeum-korean-competition-2021/voice-recognition-performance-evaluation#16]
# 주제
- 외부데이터 사용시 검증을 위한 제출 여부 

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 외부 데이터를 사용하여 학습하면, 검증시에 사용한 외부 데이터또한 제출해야 하나요?

**Comment by vetaerang** [comment]
@jade0520  안녕하세요!
외부 데이터를 사용하여 학습하면, 검증시 학습에 사용한 외부 데이터 또한 제출해주셔야 합니다. 
감사합니다.

**Comment by jade0520** [comment]
@taerangi 님 답변 감사드립니다. 그러면 검증 후, 제출한 데이터는 삭제해주시나요? 규정은 확인했으나, 추가 자료에 외부데이터가 포함되는 것인지 궁금합니다.
![image](https://user-images.githubusercontent.com/27474385/137432955-50009ad5-0d16-436b-8637-28b71fefc61b.png)

**Comment by vetaerang** [comment]
@jade0520 재현성 검증 단계에서 참가자분들께 요청드리는 자료에는 
리더보드 점수를 복원할 수 있는 소스코드, 학습에 사용된 pre-trained model 및 외부 데이터가 포함됩니다.
제출해주신 자료들은 오직 재현성 검증을 위해서만 활용되며(외부유출 금지), 전체 대회가 종료된 후에 파기할 예정입니다.
