### ISSUE TITLE
[NSML] GPU device_count가 1개로 나오는 문제

### ISSUE THREAD

**Issue by lifefeel** [hunminjeongeum-korean-competition-2021/voice-recognition-performance-evaluation#17]
# 주제
- 사용 가능한 GPU 갯수가 1개로 나옵니다.

# 상황 (자세히 작성해주시면 좋습니다.)
- 멀티 GPU를 사용하고 싶어서 `torch.cuda.device_count()`로 사용가능한 디바이스 수를 출력해보니 계속 1개로 나옵니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 사용 가능한 GPU가 팀당 2개씩이라고 들었는데, 혹시 시스템 설정이 잘못된 건인가요?

# 기타 문의 사항
-

**Comment by bluebrush** [comment]
nsml run -d XXX -g 2  이렇게 실행하셨을까요? 
nsml ps에서 아무 것도 없는 상태라면, (자원 반납 시간 1-3분 지연 가능성 있긴하지만)
`nsml run -d XXX -g 2 -c 14 --memory 150G  ` 이렇게 실행가능할꺼에요.

**Comment by bluebrush** [comment]
@lifefeel 
GPU 1개 나온 세션 ID 알려주시면 좀 더 잘 확인가능할것 같아요.

**Comment by lifefeel** [comment]
@bluebrush `-g 2` 옵션을 주니까 2개로 됩니다. 다만 gpu가 2개짜리인 디바이스가 자주 나오지 않아서 오래 기다려야 되네요.

이게 정상인 것이지요?

**Comment by bluebrush** [comment]
@lifefeel 님, GPU node가 팀전용으로 할당되어 있습니다 매 실행마다 동일한 GPU node로 할당되며, 세션옵션에 따라 나누어 사용하기도 하고, 2장을 한번에 사용하기도 합니다. nsml status -v -r 옵션으로 확인가능하시고요, 만약 일시적으로 2개가 아니라면, 이전에 돌린 1개 짜리 세션이 종료된지 1-2분 정도 지나지 않았을 것으로 예상됩니다. 해당 GPU 노드는 다른 팀에서는 사용하지 않으니 이부분 참고바랍니다.

**Comment by lifefeel** [comment]
네 감사합니다.
