### ISSUE TITLE
[NSML] 2GPU 활용 불가 제보

### ISSUE THREAD

**Issue by senti-mkyu** [hunminjeongeum-korean-competition-2021/voice-recognition-performance-evaluation#18]
# 주제
- 저희 팀에 할당된 gpu 2장이 사용이 안되는것같습니다.

# 상황 (자세히 작성해주시면 좋습니다.)
- 각 task당 같은 코드, 같은 인자로 session run 하였는데, 한쪽은 gpu usage가 납득할정도로 사용되고있는데
- 다른 한쪽은 gpu usage가 0입니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 
![image](https://user-images.githubusercontent.com/19186509/137491147-7d08e07f-5c5e-4cce-9a9d-36c843f64d66.png)

# 기타 문의 사항
- 감사합니다.

**Comment by bluebrush** [comment]
@aod1310 님, 아마도 초기 dataset 준비, package 설치 등으로 gpu util이 낮았던 것 같습니다. 
문의하신 세션 정상적으로 실행되는 것으로 보여집니다. 
https://ai.nsml.navercorp.com/admin/monitor/overview/nia1022/stt_1/31

**Comment by senti-mkyu** [comment]
@bluebrush 안녕하세요.
해당 세션이 정상작동하는것에 비해 gpu사용률도 낮고, 같이 돌리고있는 학습 세션에 비해 epoch수도 너무 차이가납니다.
학습 시작 이전에 global mvn을 위해 학습데이터를 전부 피쳐변환해서 sum, sqaure를 누적하는데 이 작업의 속도도 차이났구요.

다른 세션과 코드랑 인자도 같고 1분간격으로 세션을 생성했는데 이런 차이가 나는게 이상한것같습니다.

**Comment by bluebrush** [comment]
@aod1310 님, nia1022/stt_1/31 에 대해서 동일 코드, 동일 옵션으로 다른 GPU 노드에서 실행중에 있습니다., 결과 확인 후 update하겠습니다.

**Comment by bluebrush** [comment]
@aod1310 님, 동일 코드/동일 옵션으로 다른 노드에서도 동일하게 나오고 있습니다. 
CPU 사용비율이 매우 높은 것이 특징이네요. 
dataload에서 뭔가 하는 것 같네요. 
dataload의 worker 7까지 늘려도 CPU만 많이 사용하고 gpu는 거의 사용하지 않네요. 
하드웨어 문제는 아니고, S/W 이슈로 보입니다. 

![image](https://user-images.githubusercontent.com/12540235/137587743-43eb36f7-0c32-4e87-a682-802832226bc0.png)


![image](https://user-images.githubusercontent.com/12540235/137587729-70fc97ae-93a0-401e-8ba0-5748e4a886f7.png)

**Comment by senti-mkyu** [comment]
@bluebrush 
늦은시간까지 도움주셔서 감사합니다.
코드 상의 문제를 더 확인해봐야겠네요. 감사합니다 :)

**Comment by bluebrush** [comment]
CPU 7개로 하루정도 실행한 Graph 첨부해드립니다. GPU util 평균값이 어느 정도 나오네요. 

![image](https://user-images.githubusercontent.com/12540235/137633364-73e5a3e7-aa75-4180-b774-0a8bb341d253.png)

**Comment by senti-mkyu** [comment]
@bluebrush 늦은시간 감사합니다.
저희도 개인적으로 디버깅해보았는데, librosa.load에서 많은 시간을 소요한 것으로 파악되었습니다.
torchaudio.load혹은 soundfile.read로 해결하였습니다. 감사합니다.🙂
