### ISSUE TITLE
[NSML] 제출 실패 문의

### ISSUE THREAD

**Issue by lifefeel** [hunminjeongeum-korean-competition-2021/voice-recognition-performance-evaluation#19]
# 주제
- 제출 시 응답이 없어서 실패하는 상황

# 상황 (자세히 작성해주시면 좋습니다.)
- 계속 실패하여 추론시간초과로 생각하고 데이터 양을 줄여서 여러번 올려봤습니다. 그래도 같은 문제가 발생합니다. 추론 중에 에러가 뜨는 것인지.. 어떤 문제인지 확인이 안되는데 확인을 해주실 수 있나요?

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
제출 후 아래와 같은 메시지가 뜹니다.

```
Building docker image. It may take a while
.......nia1003/stt_1/120: Session ready
nia1003/stt_1/120: Load model
load nsml model takes 0.07876110076904297 seconds
.Infer test set. The inference should be completed within 3600 seconds.
Error: Session does not respond
```

# 기타 문의 사항
-

**Comment by bluebrush** [comment]
@lifefeel 님, 
`nsml submit ... ` 전체 command line 확인 가능할까요?

**Comment by bluebrush** [comment]
혹시, 1시간 지났을가요?

**Comment by lifefeel** [comment]
네 1시간이 넘게 지났습니다. 

커맨드는 아래와 같습니다.

`nsml submit nia1003/stt_1/120 best`

**Comment by bluebrush** [comment]
1시간 이내 끝나야하는데 그렇지 않아서 강제 종료된 것 같습니다. 
1시간 이내로 Infer를 종료할 수 있도록 하셔야 할 것 같습니다.

**Comment by Choiuijin1125** [comment]
@bluebrush 안녕하세요. 혹시 `nsml submit` 시 `numl run -g 2 -c 14` 와 같이 자원할당을 할 수 있는 매개변수가 있나요 ?

저도 제가 만든 코드에서 위와 같은 에러가 발생해서 제공된 베이스라인 코드로 1epoch 학습 한 후 제출을 하니 동일 에러가 발생하였습니다.

**Comment by lifefeel** [comment]
여러 환경에서 다량의 데이터로 확인해본 결과 CUDA 런타임에러가 나면서 프로그램이 종료되지 않았었습니다. 

에러 상황에 대한 처리를 통해 지금은 해결되었습니다.
