### ISSUE TITLE
[NSML] GPU 자원 할당 문의

### ISSUE THREAD

**Issue by Choiuijin1125** [hunminjeongeum-korean-competition-2021/voice-recognition-performance-evaluation#20]
# 주제
- 특정 세션 종료 후 가용한 GPU가 터미널에서 1개만 보여지고 있습니다.
- 

# 상황 (자세히 작성해주시면 좋습니다.)
- 특정 세션 종료 후 1시간이 지났는데도 가용한 GPU가 하나만 보여짐, 
- NSML 페이지에서는 가용 GPU 가 두개로 보여짐
- `nsml run -e main.py -d stt_1 -g 2 -c 14 --memory 150G` 으로 세션 실행 불가
- `nsml run -e main.py -d stt_1 -g 1 -c 14 --memory 150G` 으로 세션 실행 가능

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 터미널 
![image](https://user-images.githubusercontent.com/32811094/137609588-ec9d7dcb-28c9-47c6-bdfa-2b18dd3a5cd5.png)

- NSML 페이지
![image](https://user-images.githubusercontent.com/32811094/137609594-ee00a5c7-d229-4015-aef2-3c479d12601a.png)

# 기타 문의 사항
-

**Comment by bluebrush** [comment]
@Choiuijin1125 님, 불편을 드려서 죄송합니다. 
1GPU의 H/W 오류로 보여집니다. 

#### 할당 받으시는 노드를 변경하였습니다. 
### 기존 노드의 점검을 월요일 오후 8시 전후로 진행하려고 합니다. 
18일 0:15분 이전에 실행한 세션은 정보가 삭제될 수 있으니 이 부분에 대한 확인 요청드립니다.

**Comment by Choiuijin1125** [comment]
안녕하세요. @bluebrush 님 네 괜찮습니다. 언제든 괜찮으니 시간에 부탁드립니다 !
