### ISSUE TITLE
[NSML] Submit시 CPU 자원 할당으로 인한 제출이 안되는 상황입니다. 

### ISSUE THREAD

**Issue by kimkwangho82** [hunminjeongeum-korean-competition-2021/voice-recognition-performance-evaluation#22]
# 주제
- Submit시 CPU 자원 할당으로 인한 제출이 안되는 상황입니다. 

# 상황 (자세히 작성해주시면 좋습니다.)
- 1GPU(with 8cpu) 로 학습 중에, submit시 CPU 자원 할당 문제로 제출이 되고 있지 않는 상황입니다. 

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 
![image](https://user-images.githubusercontent.com/1249794/137709922-c226431e-a4a4-437f-b861-f38527df098b.png)

# 기타 문의 사항
-

**Comment by bluebrush** [comment]
@kimkwangho82 님, #21 변경으로 인한 현상입니다. 
음성 인식분야에 대해서 전체 참가자의 CPU 쿼터를 변경하였습니다. 
변경전 14
변경후 16
다시 시도하시면 동작할 것 같습니다.

**Comment by kimkwangho82** [comment]
@bluebrush 넵 submit 잘 동작합니다. 감사합니다.
