### ISSUE TITLE
[NSML] Submit시 stop session 실패로 인한 중

### ISSUE THREAD

**Issue by swigls** [hunminjeongeum-korean-competition-2021/voice-recognition-performance-evaluation#27]
# 주제
- nsml submit 실패 및 디버깅 불가

# 상황 (자세히 작성해주시면 좋습니다.)
-  nsml run을 통해 checkpoint를 save하는데까지는 정상적으로 끝났습니다.
-  nsml submit 커맨드 입력 시, stop session이 실패했다는 문구만 뜨고 에러가 납니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
-  "nsml submit --test nia1001/stt_1/111 1" 실행 시  다음과 같은 log만 뜨고 중단됩니다.

![제목 없음](https://user-images.githubusercontent.com/5536540/137958774-ceb5ba74-fc2b-4fd0-b1bc-8be8fd1d5cb8.png)

# 기타 문의 사항
-

**Comment by bluebrush** [comment]
@swigls 님, 여기서 힌트확인이 가능하실지요?
https://ai.nsml.navercorp.com/terminal/nia1001/stt_1/113

**Comment by swigls** [comment]
아래와 같이 나옵니다. 
![image](https://user-images.githubusercontent.com/5536540/138039190-ff84752c-01e0-46dc-a61b-379f83f726f6.png)

mode, paused가 포함된 argparser관련해서는 baseline코드의 것을 그대로 썼습니다.
훈련 때는 문제가 발생하지는 않았습니다.
![image](https://user-images.githubusercontent.com/5536540/138039390-019200cf-90e3-488e-a78d-5afc8e1bbb0b.png)

**Comment by swigls** [comment]
해당 오류는 제가 추가한 코드의 argparser로 인한 오류로 확인되었습니다.
