### ISSUE TITLE
[NSML] Session이 시작하지 않고 Allocating만 출력

### ISSUE THREAD

**Issue by james0248** [hunminjeongeum-korean-competition-2021/voice-recognition-performance-evaluation#28]
# 주제
- Session이 시작을 안하고 stop을 하려고 해도 실패

# 상황 (자세히 작성해주시면 좋습니다.)
- stt_2 데이터셋에 대해 처음으로 코드를 돌렸는데 session이 시작을 하지 않습니다. 또한, session을 멈추려고 해도 에러가 발생합니다. cli, 웹페이지 모두에서 시도해봤습니다

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
-
<img width="1914" alt="Screen Shot 2021-10-20 at 11 41 13" src="https://user-images.githubusercontent.com/38637195/138019274-b1e6a037-382b-4753-becb-960db200aa1b.png">
<img width="594" alt="Screen Shot 2021-10-20 at 11 44 48" src="https://user-images.githubusercontent.com/38637195/138019588-60a576e0-b8d2-4234-83a9-a1ba443d074c.png">
 

# 기타 문의 사항
-

**Comment by james0248** [comment]
```
nsml rm [session_name]
```
으로 해결했습니다

**Comment by bluebrush** [comment]
@james0248 님, 
docker image pull과 내부에 명시한 pip install 등의 package 설치로 인한 시간 지연으로 보입니다. 혹시, nsml rm 으로 잘 안되시면, nsml rm -f 로도 한번 시도해보시면 좋을 것 같습니다.
