### ISSUE TITLE
[NSML] memory 사용량 제한 문의

### ISSUE THREAD

**Issue by kaen2891** [hunminjeongeum-korean-competition-2021/voice-recognition-performance-evaluation#29]
# 주제
-  안녕하세요. ram memory 사용 제한이 있는지 여쭤보고 싶습니다. 아래와 그림과 같이 에러가 생겨서 문의드립니다.
![image](https://user-images.githubusercontent.com/46586785/138021072-ffdabfdd-773d-4331-83d3-702523973f1d.png)

![image](https://user-images.githubusercontent.com/46586785/138021101-45e4772b-cf89-478b-b36c-167b33fcf79e.png)

현재 사용량
![image](https://user-images.githubusercontent.com/46586785/138021152-02b6044f-88d3-4613-9b85-1855f78f5684.png)

- 메모리 100까지는 안되는 것인가요?
- @bluebrush님 도와주세요!

**Comment by kaen2891** [comment]
Memory를 설정 하지 않고 default로 하면 실행이 되는데, 제한되는 memory가 몇인지 궁금합니다.

**Comment by bluebrush** [comment]
@kaen2891 님, 
100 -> 100G 
하셔야..
160GB 까지 가능할 것 같아요

**Comment by kaen2891** [comment]
@bluebrush님, 아 G를 붙여야하는군요 감사합니다 ㅎㅎㅎ

**Comment by bluebrush** [comment]
default = 24G, 
--shm-memory = 1G
총 25G  사용합니다.

**Comment by kaen2891** [comment]
@bluebrush님, 숫자만 치면 되는지 알았는데... G를 붙이니 잘 되는 것 같습니다. 감사합니다!
