### ISSUE TITLE
[H/W 장애 공지] 크누보이스 팀, submit 중 H/W 오류 상황 알려드립니다. 

### ISSUE THREAD

**Issue by bluebrush** [hunminjeongeum-korean-competition-2021/voice-recognition-performance-evaluation#31]
재부팅된 시간 : 2021. 10. 20. (수) 22:35

submit of nia1009/stt_1/227
`nia1009/stt_1/238` 세션 구동중 H/W 장애로 해당 노드가 재부팅되었습니다. 

https://ai.nsml.navercorp.com/admin/monitor/overview/nia1009/stt_1/238
정상 제출 여부의 확인이 필요하여 알려드립니다. 

불편을 드려서 죄송합니다. 

@kaen2891 님

**Comment by kaen2891** [comment]
@bluebrush님, 저희쪽 문제로 생긴건가요? 아님 기기 문제로 생긴건가요? 스크립트 짜서 1시간마다 submit 해놓을 수 있도록 해놨었습니다.

**Comment by bluebrush** [comment]
@kaen2891 사용자와 관련없이 서버문제입니다.
