### ISSUE TITLE
[NSML] NSML AutoML 사용관련

### ISSUE THREAD

**Issue by Ldoun** [hunminjeongeum-korean-competition-2021/voice-recognition-performance-evaluation#33]
# 주제
- NSML 홈페이지를 봐보면 Auto ML : automatically find the best hyperparameter of user's model 라는 기능이 있던데 혹시 사용 가능한가요? NSML Documentation에 AutoML 관련 기능에 대한 설명이 없더라고요.

**Comment by bluebrush** [comment]
@Ldoun 님, 아쉽게도 대회에서는 Auto ML을 제공하고 있지 않습니다.

**Comment by Ldoun** [comment]
아쉽네요. 답변 감사합니다!
