### ISSUE TITLE
[NSML] submit 1시간 간격 및 최종 점수

### ISSUE THREAD

**Issue by LVCSRer** [hunminjeongeum-korean-competition-2021/voice-recognition-performance-evaluation#34]
# 주제
- 음성인식의 경우 2개의 문제를 진행하는데 각 문제별 1시간 간격인지 합쳐서 1시간 간격인지 문의드립니다. 그리고 최종 순위는 두 개의 스코어 단순합산으로 결정 되는건가요?

# 상황 (자세히 작성해주시면 좋습니다.)
- 

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 

# 기타 문의 사항
-

**Comment by vetaerang** [comment]
@LVCSRer 안녕하세요.
submit시 추론 제한 시간은 각 문제별로 1시간 이내입니다.
최종 순위는 두 문제 스코어의 단순 합산으로 결정됩니다.
감사합니다.

**Comment by LVCSRer** [comment]
@taerangi  답변 감사드립니다. 제가 설명을 제대로 못드린 것 같은데 추론시간을 문의드린 것이 아니라 제출 간격을 문의드린건데요. 1시간에 1번 제출 (하루에 24회)하는 부분에 대한 문의입니다. 예를 들어 stt_1 을 제출했을때 stt_2 제출은 앞의 제출과 독립적으로 제출 가능한것인가에 대한 것입니다.

**Comment by vetaerang** [comment]
@bluebrush 님 답변 가능하실까요??

**Comment by bluebrush** [comment]
@LVCSRer  님, 
stt_1 , stt_2 각각 1시간 간격이며, 서로 제약의 관련이 전혀 없습니다. 완전히 독립된 상태입니다.

**Comment by LVCSRer** [comment]
확인 감사합니다!
