### ISSUE TITLE
[NSML] No space left on device 에러 발생

### ISSUE THREAD

**Issue by james0248** [hunminjeongeum-korean-competition-2021/voice-recognition-performance-evaluation#35]
# 주제
- 디스크가 가득 차 훈련이 안되고 이후 추가 코드 제출이 불가

# 상황 (자세히 작성해주시면 좋습니다.)
- 코드 중 데이터셋을 디스크에 저장하는 코드가 있는데 몇번 실행하고 나니 디스크가 가득 차 코드 제출이 안됩니다. 혹시 몰라 NSML에 저장되어있는 모델 몇개를 지워봤지만 소용이 없는것 같습니다

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
이전 제출 이후 시간이 많이 지났음에도 코드 제출이 되지 않습니다
<img width="870" alt="Screen Shot 2021-10-22 at 11 27 13" src="https://user-images.githubusercontent.com/38637195/138383420-89e4f3b1-b35a-4b5a-a9bd-09e1bcf9f4ca.png">

마찬가지로 훈련도 디스크에 잔여 공간이 없어 더 이상 진행이 안됩니다
<img width="719" alt="Screen Shot 2021-10-22 at 11 22 01" src="https://user-images.githubusercontent.com/38637195/138382972-4074bf9a-e1d0-4470-9f84-731572c22ccb.png">
 

# 기타 문의 사항
-

**Comment by bluebrush** [comment]
@james0248 님, 몇 가지 확인요청드립니다. 
1. `nsml info` 실행 값
2. session ID 확인 가능할까요?

**Comment by james0248** [comment]
@bluebrush 
저장되어있던 세션을 여러개 날리니 지금은 해결되었습니다. 세션이 너무 많이 남아있으면 오류가 발생하는 것인가요?
`nsxml info` 실행결과
```bash
 nsml info
--------------------------------------  -------
Number of sessions                      126
Number of sessions generated by automl  0
Total model size                        7.06 GB
Total number of Checkpoints             3
Total number of dataset                 0
Total dataset size                      0 B
--------------------------------------  -------
```
session ID는 `nia1030/stt_1/391`입니다

**Comment by bluebrush** [comment]
@james0248 님, 
네에, 세션 지우면서 공간이 확보된 것을 보여집니다. 
local GPU node에 2TB가 할당되어 있으며, 
위의 126개 세션에서 아래의 공간을 차지하고 있습니다. 
최종 leaderboard에 게시된 세션이나, 보존할 가치가 있는 세션만 남기시고 지우시는 것도 도움이 되실 것 같습니다. 
![image](https://user-images.githubusercontent.com/12540235/138394453-72d7a7c4-d685-45ea-a3ee-8860a1cfdcdf.png)
