### ISSUE TITLE
[NSML] 본선 관련 문의

### ISSUE THREAD

**Issue by Choiuijin1125** [hunminjeongeum-korean-competition-2021/voice-recognition-performance-evaluation#36]
안녕하세요.

혹시 본선에 진출하게 되면

대회 진행 방식이 어떻게 되는지 알 수 있을까요 ?

1. 문제 3(명령어), 문제 4(자유 대화), 문제 5(방언) 데이터를 사용하여 대회 참여
2. 문제 3, 문제 4의 점수는 예선 점수로 fix, 문제 5 데이터를 사용하여 대회 참여

감사합니다.

**Comment by vetaerang** [comment]
@Choiuijin1125 안녕하세요
1) 문제 3(명령어), 문제 4(자유 대화), 문제 5(방언) 데이터를 사용하여 대회 참여

방식으로 본선 대회가 진행될 예정입니다.

감사합니다.

**Comment by Choiuijin1125** [comment]
감사합니다.
