### ISSUE TITLE
[NSML] 세션 진행중 모델 제출 가능 여부 문의

### ISSUE THREAD

**Issue by james0248** [hunminjeongeum-korean-competition-2021/voice-recognition-performance-evaluation#37]
# 주제
- session이 돌아가는 중에 저장된 모델을 제출할 수 있는지 여부 문의

# 상황 (자세히 작성해주시면 좋습니다.)
- 현재 nsml 사용법을 늦게 익혀 학습하고 있는 session이 대회가 끝나기 전에 완료될지가 미지수입니다. 혹시 제가 현재 학습하고 있는 session에서 nsml.save()를 통해 저장되어있는 모델이 있다면 이를 제출에 이용할 수 있나요? 아니면 무조건 session이 끝날 때까지 기다려야 하나요? 
- 만약 후자라면 중간에 session을 stop 시켜도 model.save()를 통해 저장한 모델은 남아있는 것인가요? 감사합니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 

# 기타 문의 사항
-

**Comment by bluebrush** [comment]
@james0248 님, 
nsml model ls [session-id]에서 표현되는 세션의 종료 여부와 관련 없이, 바로 submit을 진행할 수 있습니다.
