### ISSUE TITLE
[Dataset] training 데이터 다운로드 및 CER 계산 방법 문의

### ISSUE THREAD

**Issue by Choiuijin1125** [hunminjeongeum-korean-competition-2021/voice-recognition-performance-evaluation#4]
안녕하세요. 
1. Training 데이터를 별도로 다운 받을 수 있는지 문의 드립니다.

2. 1번 사항이 제한 될 경우 CER, WER 계산시 평가 기준에 대한 세부 사항에 대해 문의드립니다.
    1) 숫자 표기
         - ex) '일 이 삼' 음성 발화시 정답 기준 : 1 2 3 | 1, 2, 3 | 일 이 삼 등
         - ex) '2023년' 음성 발화시 정답 기준 : 이천이십삼년 | 2023년 등

    2) 영어 발음 표기 
        - ex) 축약어 'SNS' 발화시 정답 기준 : 에스엔에스 | SNS 등
        - ex) '뉴욕 날씨 알려줘' : '뉴욕 날씨 알려줘' | NewYork 날씨 알려줘 등
   
    3) 간투어 표기
        - ex) 역량 평가시 '아', '그', '저' 등의 간투어 발화시 '아/', '그/', '저/' 등이 정답으로 처리되었는데, 예선도 동일한가요?

**Comment by dacon-murdoch** [comment]
안녕하세요.
데이터는 local로 다운받아 분석을 진행할 수 없습니다.
2. 영어 발음의 경우 (ex. NewYork -- > 뉴욕 한글로 표시) 한글로 기재하시면 됩니다.
3. "/"표기는 제외하여 학습하시면 됩니다. 
감사합니다.
