### ISSUE TITLE
[NSML]GPU 사용법 + 질문 추가

### ISSUE THREAD

**Issue by jade0520** [hunminjeongeum-korean-competition-2021/voice-recognition-performance-evaluation#5]
# 주제
-  ~~세션 삭제 후에도 메모리가 비워지지 않는 상황~~

# 상황 (자세히 작성해주시면 좋습니다.)
- ~~세션 실행 후 오류로 세션이 정지되면, 코드 수정 후 다시 run 하고 이전의 세션은 항상 삭제를 했습니다.  다섯 번째 세션 쯤에 메모리 부족으로 오류가 발생했고, Resources 확인해보니 메모리가 아래 사진처럼 꽉 차있었습니다.~~
![image](https://user-images.githubusercontent.com/27474385/136670728-33257af5-2dd8-4462-aad7-2ee12a381253.png)

- ~~좀비세션인가 확인했는데 조회는 안되었구요.~~
![image](https://user-images.githubusercontent.com/27474385/136670753-ef12a4e0-9c99-4952-bc11-88d4f750b39f.png)

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- ~~혹시 세션 삭제 시에 따로 메모리를 비워줘야 하나요?~~
- ~~GPU 메모리 관리하는 방법있다면 안내 부탁드립니다.~~
- ~~다른 부문 이슈에서도 비슷한 일([1](https://github.com/hunminjeongeum-korean-competition-2021/dialogue-summarization/issues/8#issue-1021735794), [2](https://github.com/hunminjeongeum-korean-competition-2021/speaker-recognition/issues/5#issue-1021698677))이 발생하는 것을 보아 공통적으로 공지 주시면 도움이 많이 될 것 같습니다. 감사합니다!~~

# 기타 문의 사항
-

**Comment by jade0520** [comment]
안녕하세요, @bluebrush 님! 
[다른 이슈](https://github.com/hunminjeongeum-korean-competition-2021/dialogue-summarization/issues/8#issuecomment-939409495)에서 답변 달아주신 것을 확인하고 지금 다시 해보는 중인데 CPU로는 잘 돌아가는 것 같습니다!

1. 그런데 여전히 GPU는 메모리 부족으로 사용할 수 없습니다. 혹시 다른 팀들이 사용 중 일때는 제약을 받나요? 
![image](https://user-images.githubusercontent.com/27474385/136684713-be1ab338-0c7f-43c1-8bd8-b5b3aa6d7139.png)

2. 또, 궁금한 것이 위에 첨부드린 사진이 "위 자원뷰는 공용 pool에 대한 내용"이라고 말씀 주셨는데, 그럼 사이트에서 아래와 같은 다른 표시들은 어떤 의미인지 알 수 있을까요?  아래 사진들은 사용할 수 있는 GPU를 모두 사용했다고 이해해도 될까요?
![image](https://user-images.githubusercontent.com/27474385/136684521-544feb6c-9f7b-4a58-b157-a182b3b30182.png)
![image](https://user-images.githubusercontent.com/27474385/136684541-3b432297-3597-43fd-b82d-0be3fb1bbdb6.png)

3. 또한, 답변 주신 것처럼 `nsml status -r `이나 `nsml status -r  -v` 를 하면 아래 사진과 같이 알 수 없는 옵션이라고 뜹니다. 혹시 다른 명령어를 알 수 있을까요? 
![image](https://user-images.githubusercontent.com/27474385/136684599-d265a088-a7a6-4444-8b57-b78304c3a167.png)
![image](https://user-images.githubusercontent.com/27474385/136684610-2ddf3db1-2f63-41df-90db-a619e9273f7b.png)

주말인데도 해결을 위해 노력해주심에 감사드립니다.ㅠㅠ

**Comment by ruruca** [comment]
동일한 상황이고, nsml rm 후 다시 실행시 에러 발생 됩니다.  (추가로)

```shell
INFO[2021/10/10 23:58:40.822] .nsmlignore check - start                    
INFO[2021/10/10 23:58:40.822] .nsmlignore check - done                     
INFO[2021/10/10 23:58:40.858] file integrity check - start                 
INFO[2021/10/10 23:58:40.858] file integrity check - done                  
INFO[2021/10/10 23:58:40.859] data.py 4.0 KiB - start                      
INFO[2021/10/10 23:58:40.859] data.py 4.0 KiB - done (1/4 25.00%) (4.0 KiB/23 KiB 17.44%) 
INFO[2021/10/10 23:58:40.859] main.py 9.8 KiB - start                      
INFO[2021/10/10 23:58:40.859] main.py 9.8 KiB - done (2/4 50.00%) (14 KiB/23 KiB 59.68%) 
INFO[2021/10/10 23:58:40.859] setup.py 159 B - start                       
INFO[2021/10/10 23:58:40.859] setup.py 159 B - done (3/4 75.00%) (14 KiB/23 KiB 60.35%) 
INFO[2021/10/10 23:58:40.859] stt_model.py 9.2 KiB - start                 
INFO[2021/10/10 23:58:40.860] stt_model.py 9.2 KiB - done (4/4 100.00%) (23 KiB/23 KiB 100.00%) 
.....Process Process-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/app/src/nsml_cli/sessions/session_prepare.py", line 124, in build_and_launch
    build_session(ctx=ctx, session=session, verbose=verbose, local_path=dataset_path)
  File "/app/src/nsml_cli/sessions/session_prepare.py", line 36, in build_session
    exclude_containers=None)
  File "/app/src/nsml_cli/datasets/dataset.py", line 129, in download_dataset
    err=False).split('\n')
  File "/app/src/nsml_cli/datasets/dataset.py", line 357, in docker_exec
    'exec', *(['-t'] if verbose else []), container_name, *args, interactive=False, err=err, encrypted=ctxobj
  File "/app/src/nsml_cli/cluster.py", line 91, in docker
    return docker(self.address, *args, **kwargs)
  File "/app/src/nsml_cli/docker.py", line 88, in docker
    return _run_docker_cmd(args, interactive, err, **kwargs)
  File "/app/src/nsml_cli/docker.py", line 78, in _run_docker_cmd
    out = check_output(cmd, stderr=-2 if err else devnull)
  File "/usr/local/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', '--config', '/tmp/nia1037', '-H', 'tcp://10.41.93.129:2375', 'exec', 'minio_client', 'ls', '/data']' returned non-zero exit status 126.

Session nia1037/stt_1/2 is started
```

**Comment by jade0520** [comment]
@ruruca 저도 위와 비슷한 문구가 떴는데, 세션 allocated 상태이더라고요. 혹시 해결 되셨나요?
